mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    login_view,
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    UserUpdateView,
)

app_name = 'myauth'

urlpatterns = [
    # path('login/', login_view, name='login'),
    path(
        'login/',
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login',
    ),
    # path('logout/', logout_view, name='logout'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/<int:pk>/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('about-me/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
# import debug_toolbar


urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('app_pages/', include('app_pages.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap' )
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

mysite/shopapp/urls.py
# from django.views.decorators.cache import cache_page

from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    OrderCreateView,
    ProductDeleteView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
)

app_name = 'shopapp'


routers_product = DefaultRouter()
routers_product.register('products', ProductViewSet)

routers_order = DefaultRouter()
routers_order.register('orders', OrderViewSet)

urlpatterns = [
    # path('', cache_page(60 * 3)(ShopIndexView.as_view()), name='index'),
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers_product.urls)),
    path('api/', include(routers_order.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='products_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(),name='product_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='products-feed'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/export/', OrdersExportView.as_view(), name='orders-export'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse


def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'tech_products'
        # verbose_name_plural = 'products'

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    create_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def get_absolute_url(self):
        return reverse('shopapp:products_details', kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name!r})'


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/images/{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm
from shopapp.models import Product, Order
from django import forms


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount', 'preview',

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = 'user', 'products', 'delivery_address', 'promocode'


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""

from csv import DictWriter
import logging
from timeit import default_timer
from django.contrib.auth.models import Group

from django.shortcuts import render, reverse, redirect  # get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Product, Order, User, ProductImage
from .forms import ProductForm, OrderForm, GroupForm

from django.views import View
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)

from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from .common import save_csv_products, save_csv_orders

from django_filters.rest_framework import DjangoFilterBackend
from .serializers import ProductSerializer, OrderSerializer

from drf_spectacular.utils import extend_schema, OpenApiResponse

from django.contrib.syndication.views import Feed

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

log = logging.getLogger(__name__)


class LatestProductsFeed(Feed):
    title = 'Products (latest)'
    description = 'Updates on changes products'
    link = reverse_lazy('shopapp:products_list')

    def items(self):
        return Product.objects.filter(archived=False).all()

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        if item.description:
            return item.description[:20]
        return "No description there"


@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [SearchFilter, OrderingFilter, ]
    search_fields = ['name', 'description', ]
    filterset_fields = [
        'pk',
        'name',
        'description',
        'price',
        'discount',
        'create_by',
        'archived',
    ]
    ordering_fields = [
        'pk',
        'name',
        'price',
        'discount',
        'create_by',
    ]
    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        # print('hello products list!')
        return super().list(*args, **kwargs)

    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        },
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response

    @action(detail=False, methods=["post"], parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request) -> Response:
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, ]
    filterset_fields = [
        'delivery_address',
        'promocode',
        'user',
        'products',
    ]
    ordering_fields = [
        'delivery_address',
        'promocode',
        'user',
    ]

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content_type="text/csv")
        filename = "orders-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'delivery_address',
            'promocode',
            'user',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for order in queryset:
            writer.writerow({
                field: getattr(order, field)
                for field in fields
            })
        return response

    @action(detail=False, methods=["post"], parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request) -> Response:
        orders = save_csv_orders(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(orders, many=True)
        return Response(serializer.data)


class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
        }
        log.debug('Products for shop index: %s', products)
        log.info('Rendering shop index')
        print('shop index context:', context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        # url = reverse('shopapp:groups_list')
        # return redirect(url)
        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    # model = Product
    context_object_name = 'product'
    queryset = Product.objects.prefetch_related('images')


class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


# LoginRequiredMixin, UserPassesTestMixin,
class ProductCreateView(CreateView):
    # def test_func(self):
    #     return self.request.user.is_superuser or \
    #         self.request.user.has_perm('shopapp.add_product')
    #
    #
    # def form_valid(self, form):
    #     form.instance.create_by = self.request.user
    #     return super().form_valid(form)

    model = Product
    fields = 'name', 'price', 'description', 'discount', 'preview',
    # fields or -> form_class = ProductForm
    success_url = reverse_lazy('shopapp:products_list')


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_superuser or (
                self.request.user.has_perm('shopapp.change_product') and
                self.request.user == self.get_object().create_by)

    model = Product
    # fields = 'name', 'price', 'description', 'discount', 'preview',
    form_class = ProductForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:products_details',
            kwargs={'pk': self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):
            ProductImage.objects.create(product=self.object, image=image)
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


# def create_product(request: HttpRequest) -> HttpResponse:
#     if request.method == "POST":
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             url = reverse('shopapp:products_list')
#             return redirect(url)
#     else:
#         form = ProductForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'shopapp/product_form.html', context=context)


# def new_create_order(request: HttpRequest):
#     if request.method == "POST":
#         form = OrderForm(request.POST)
#         if form.is_valid():
#             form.save()
#             url = reverse('shopapp:orders_list')
#             return redirect(url)
#     else:
#         form = OrderForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'shopapp/order_form.html', context=context)

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
</head>
<body>

{% block body %}
    Base body
{% endblock %}

<div>
    <br>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h3>No groups yet</h3>
        {% else %}
            <ul>
                {% for group in groups %}
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for permission in group.permissions.all %}
                                <li>{{ permission.name }}
                                    (<code>{{ permission.codename }}</code>)
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Delete order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete order #{{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order #{{ object.pk }}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
        <p>Order by {% firstof object.user.first_name object.user.username %}</p>
        <p>Promocode <code>{{ object.promocode }}</code></p>
        <p>Delivery address {{ object.delivery_address }}</p>
        <div>
            Product in order:
            <ul>
                {% for product in object.products.all %}
                    <li>{{ product.name }} for ${{ product.price }}</li>
                {% endfor %}
            </ul>
        </div>
        <br>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}"
        >Update order #{{ object.pk }}</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:order_delete' pk=object.pk %}">Delete order</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Create order</button>
        </form>
    </div>

    <div>
        <br>
        <a href="{% url 'shopapp:products_list' %}">Products list</a>
    </div>

    <div>
        <br>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
                    >Details #{{ order.pk }}</a></p>
                    <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                    <p>Promocode <code>{{ order.promocode }}</code></p>
                    <p>Delivery address {{ order.delivery_address }}</p>
                    <div>
                        Product in order:
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for ${{ product.price }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                <br>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No order yet</h3>
    {% endif %}

    <div>
        <br>
        <a href="{% url 'shopapp:order_create' %}">Create order</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Update order</button>
        </form>
    </div>

    <div>
        <br>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}"
        >Back to order #{{ object.pk }}</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archived {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:products_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">archived</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <br>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        <p>Created by: {% firstof product.create_by 'There is no author' %}</p>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">

        {% endif %}

        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                </div>
                <div>
                    {{ img.description }}
                </div>
            {% empty %}
                <div>No images uploaded yet</div>
            {% endfor %}
        </div>
    </div>

    <div>
        <br>
        {% if user.is_superuser or perms.shopapp.change_product and product.create_by == user %}

            <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>

        {% endif %}
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archived product</a>
    </div>
    <div>
        <br>
        <a href="{% url 'shopapp:products_list' %}">Back products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    <h1>Products:</h1>
    {% if products %}
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url "shopapp:products_details" pk=product.pk %}"
                    >Name: {{ product.name }}</a></p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>
                    <p>Created by: {% firstof product.create_by 'There is no author' %}</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">

                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <br>
        {% if perms.shopapp.add_product %}

            <a href="{% url 'shopapp:product_create' %}">Create a new product</a>

        {% endif %}
    </div>

    <div>
        <br>
        <a href="{% url 'shopapp:order_create' %}">Create order</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index!</h1>

    <div>
        <ul>
            {% for name, price in products %}
                <li> {{ name }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length_is:'7' %}
                    <span>Lucky product</span>
                {% endif %} 
            {% empty %}
                No products here
            {% endfor %}
        </ul>
    </div>

    <div>
        Time running: {{ time_running }}
    </div>

    {% cache 100 lorem %}
        <div>
            {% lorem 3 p random %}
        </div>
    {% endcache %}

{% endblock %}