mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    login_view,
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    UserUpdateView,
)

app_name = 'myauth'

urlpatterns = [
    # path('login/', login_view, name='login'),
    path(
        'login/',
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login',
    ),
    # path('logout/', logout_view, name='logout'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/<int:pk>/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/', UsersListView.as_view(), name='users-list'),
    path('about-me/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),

    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/get/', get_session_view, name='session-get'),
    path('session/set/', set_session_view, name='session-set'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
# import debug_toolbar


urlpatterns = [
    # path('__debug__/', include(debug_toolbar.urls)),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('app_pages/', include('app_pages.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap' )
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def user_profile_picture_directory_path(instance: User, filename: str) -> str:
    return 'myauth/about-me_{pk}/profile_picture/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    profile_picture = models.ImageField(
        null=True, blank=True, upload_to=user_profile_picture_directory_path)

mysite/myauth/forms.py
from django.forms import ModelForm
from myauth.models import Profile, User
from django.contrib.auth.models import User


class UserForm(ModelForm):
    class Meta:
        model = Profile
        fields = 'profile_picture', 'bio',

mysite/myauth/views.py
from random import random
from django.views.decorators.cache import cache_page

from django.contrib.auth.decorators import (
    login_required,
    permission_required,
    user_passes_test,
)
from django.contrib.auth.forms import UserCreationForm, User, UserChangeForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView
from .forms import UserForm
from .models import Profile
from django.contrib.auth.mixins import UserPassesTestMixin


class UserUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_staff or \
            self.request.user == self.get_object().user

    model = Profile
    form_class = UserForm
    template_name = 'myauth/profile_update_form.html'

    def get_success_url(self):
        return reverse('myauth:users-list')


class UsersListView(ListView):
    model = User
    template_name = 'myauth/users-list.html'
    context_object_name = 'users'


class AboutMeView(DetailView):
    model = User
    template_name = 'myauth/about-me.html'
    context_object_name = 'user'


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')

        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {'error': 'Invalid login credentials'})


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse('myauth:login'))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


# @user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response

@cache_page(60 * 2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value: {value!r} + {random()}')


@permission_required('myauth.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f'Session value: {value!r}')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    <div>
        Products available: {% now 'u' %}
    </div>
    {% if user.is_authenticated %}
        {% cache 300 userinfo user.username %}
            <h2>Detail</h2>

            {% if user.profile.profile_picture %}
                <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.profile.profile_picture.name }}">
            {% else %}
                <p>No profile photo</p>
            {% endif %}

            <p>Username: {{ user.username }}</p>
            <p>First name: {{ user.first_name }}</p>
            <p>Last name: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Bio: {{ user.profile.bio }}</p>
        {% endcache %}
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

    <div>
        <br>
        {% if request.user.is_staff or request.user.pk == user.profile.user_id %}

            <a href="{% url 'myauth:user_update' pk=user.profile.pk %}">Update profile</a>

        {% endif %}
    </div>

    <div>
        <br>
        <a href="{% url 'myauth:users-list' %}">Back users list</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update user profile
{% endblock %}

{% block body %}
    <h1>Update user profile:</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Update</button>
        </form>
    </div>

    <div>
        <br>
        <a href="{% url 'myauth:about-me' pk=profile.user_id %}"
        >Back to user </a>
    </div>

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users:</h1>
    {% if users %}
        <div>
            {% for user in users %}
                <div>
                    {% if user.profile.profile_picture %}
                        <img src="{{ user.profile.profile_picture.url }}"
                             alt="{{ user.profile.profile_picture.name }}">
                    {% else %}
                        <p>No profile photo</p>
                    {% endif %}
                </div>
                <div>
                    <p><a href="{% url 'myauth:about-me' pk=user.pk %}"
                    >Name: {{ user.username }}</a></p>
                </div>

            {% endfor %}

        </div>

    {% endif %}

{% endblock %}